/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;

/**
 *
 * @author kosana
 */
public class Client extends javax.swing.JFrame {

    private Socket socket;
    private BufferedReader br;
    private PrintWriter pw;
    private String clientUsername = "";
    private ReceiveMessageFromServer rmfs;
    
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        this.btnRespA.setActionCommand("a)");
        this.btnRespB.setActionCommand("b)");
        this.btnRespC.setActionCommand("c)");
        this.btnRespD.setActionCommand("d)");

        
        setResizable(false);
    }

    public BufferedReader getBr() {
        return this.br;
    }
    
    public JComboBox<String> getCbUsers() {
        return this.cbUsers;
    }
    
    public JTextArea getTaQuestions() {
        return taQuestions;
    }
    
    public String getClientUsername() {
        return clientUsername;
    }
    
    public String getClientRole() {
        return tfRole.getText();
    }
    
    public void setTaQuestions(String poruka) {
        taQuestions.append(poruka + "\n");
    }
    
    public void setHelpsEnabled() {
        this.btnFriendsHelp.setEnabled(true);
        this.btnReplace.setEnabled(true);
        this.btnFiftyFifty.setEnabled(true);
    }
    
    public void setLogInWindowVisible(){
        btnLogIn.setEnabled(true);
        btnLogIn.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setEnabled(true);
        jLabel4.setVisible(true);
        tfUsername.setEnabled(true);
        tfPassword.setVisible(true);
        tfRole.setVisible(true);

        if(tfRole.getText().equals("admin")) {
            cbSet.setVisible(false);
            tfUsernameA.setVisible(false);
            tfPasswordA.setVisible(false);
            tfRoleA.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            btnAdd.setVisible(false);
            btnRemove.setVisible(false);
        } else if (tfRole.getText().equals("takmicar") || tfRole.getText().equals("takmičar")) {
            cbUsers.setVisible(false);
            tfMessage.setVisible(false);
            btnNewSet.setVisible(false);
            btnStatement.setVisible(false);
            btnFriendsHelp.setVisible(false);
            btnFiftyFifty.setVisible(false);
            btnReplace.setVisible(false);
            btnConfirmResp.setVisible(false);
            btnRespA.setVisible(false);
            btnRespB.setVisible(false);
            btnRespC.setVisible(false);
            btnRespD.setVisible(false);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupResponse = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        spQuestions = new javax.swing.JScrollPane();
        taQuestions = new javax.swing.JTextArea();
        btnLogIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfRole = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        tfRoleA = new javax.swing.JTextField();
        tfPasswordA = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfUsernameA = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbSet = new javax.swing.JComboBox<>();
        btnStatement = new javax.swing.JButton();
        btnNewSet = new javax.swing.JButton();
        btnFiftyFifty = new javax.swing.JButton();
        btnFriendsHelp = new javax.swing.JButton();
        btnReplace = new javax.swing.JButton();
        btnRespA = new javax.swing.JRadioButton();
        btnRespB = new javax.swing.JRadioButton();
        btnRespC = new javax.swing.JRadioButton();
        btnRespD = new javax.swing.JRadioButton();
        btnConfirmResp = new javax.swing.JButton();
        tfMessage = new javax.swing.JTextField();
        cbUsers = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KVIZ");

        taQuestions.setColumns(20);
        taQuestions.setRows(5);
        spQuestions.setViewportView(taQuestions);

        btnLogIn.setText("Prijavi se");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Šifra");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Korisničko ime");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Uloga (mala slova)");

        btnAdd.setText("Dodaj korisnika");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Šifra");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Korisničko ime");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Uloga (mala slova)");

        btnRemove.setText("Ukloni korisnika");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Aktiviraj set pitanja broj ");

        cbSet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cbSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSetActionPerformed(evt);
            }
        });

        btnStatement.setText("Stanje na tabeli");
        btnStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatementActionPerformed(evt);
            }
        });

        btnNewSet.setText("Novi set pitanja");
        btnNewSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSetActionPerformed(evt);
            }
        });

        btnFiftyFifty.setText("Pola-pola");
        btnFiftyFifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiftyFiftyActionPerformed(evt);
            }
        });

        btnFriendsHelp.setText("Pomoć prijatelja");
        btnFriendsHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriendsHelpActionPerformed(evt);
            }
        });

        btnReplace.setText("Zamena pitanja");
        btnReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceActionPerformed(evt);
            }
        });

        btnGroupResponse.add(btnRespA);
        btnRespA.setText("a)");

        btnGroupResponse.add(btnRespB);
        btnRespB.setText("b)");

        btnGroupResponse.add(btnRespC);
        btnRespC.setText("c)");

        btnGroupResponse.add(btnRespD);
        btnRespD.setText("d)");

        btnConfirmResp.setText("Potvrdi odgovor");
        btnConfirmResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmRespActionPerformed(evt);
            }
        });

        cbUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUsername)
                    .addComponent(tfPassword)
                    .addComponent(tfRole, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnStatement)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewSet, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirmResp)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRespA)
                        .addGap(18, 18, 18)
                        .addComponent(btnRespB)
                        .addGap(18, 18, 18)
                        .addComponent(btnRespC)
                        .addGap(18, 18, 18)
                        .addComponent(btnRespD)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFiftyFifty, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFriendsHelp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfUsernameA)
                    .addComponent(tfPasswordA)
                    .addComponent(tfRoleA)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSet, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUsernameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPasswordA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfRoleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnRemove)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRespB)
                                    .addComponent(btnRespA)
                                    .addComponent(btnRespC)
                                    .addComponent(btnRespD))
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmResp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnStatement)
                                    .addComponent(btnNewSet))
                                .addGap(18, 18, 18)
                                .addComponent(btnFiftyFifty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReplace))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogIn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFriendsHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        tfRoleA.setVisible(false);
        tfPasswordA.setVisible(false);
        btnAdd.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        tfUsernameA.setVisible(false);
        btnRemove.setVisible(false);
        jLabel8.setVisible(false);
        cbSet.setVisible(false);
        btnStatement.setVisible(false);
        btnNewSet.setVisible(false);
        btnFiftyFifty.setVisible(false);
        btnFriendsHelp.setVisible(false);
        btnReplace.setVisible(false);
        btnRespA.setVisible(false);
        btnRespB.setVisible(false);
        btnRespC.setVisible(false);
        btnRespD.setVisible(false);
        btnConfirmResp.setVisible(false);
        tfMessage.setVisible(false);
        cbUsers.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        System.out.println("Klik na Prijavi se");
        if (this.tfRole.getText().equals("takmicar") ||
                this.tfRole.getText().equals("takmičar") ||
                this.tfRole.getText().equals("admin")) {    
            try {
                // TODO add your handling code here:
                this.socket = new Socket("127.0.0.1", 6001);
                this.br = new BufferedReader(new InputStreamReader(this.socket.getInputStream()));
                this.pw = new PrintWriter(new OutputStreamWriter(this.socket.getOutputStream()), true);
                this.clientUsername = tfUsername.getText();
                this.rmfs = new ReceiveMessageFromServer(this);
                Thread thr = new Thread(rmfs);
                thr.start();
            } catch (IOException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            btnLogIn.setEnabled(false);
            btnLogIn.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setEnabled(false);
            jLabel4.setVisible(false);
            tfUsername.setEnabled(false);
            tfPassword.setVisible(false);
            tfRole.setVisible(false);

            if(tfRole.getText().equals("admin")) {
                cbSet.setVisible(true);
                tfUsernameA.setVisible(true);
                tfPasswordA.setVisible(true);
                tfRoleA.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                btnAdd.setVisible(true);
                btnRemove.setVisible(true);
            } else if (tfRole.getText().equals("takmicar") || tfRole.getText().equals("takmičar")) {
                cbUsers.setVisible(true);
                tfMessage.setVisible(true);
                btnNewSet.setVisible(true);
                btnStatement.setVisible(true);
                btnFriendsHelp.setVisible(true);
                btnFiftyFifty.setVisible(true);
                btnReplace.setVisible(true);
                btnConfirmResp.setVisible(true);
                btnRespA.setVisible(true);
                btnRespB.setVisible(true);
                btnRespC.setVisible(true);
                btnRespD.setVisible(true);
                btnRespA.setSelected(true);
            }

            this.pw.println(tfUsername.getText() + ":" + tfPassword.getText() + ":" + tfRole.getText());  
        }
        else {
            this.taQuestions.setText("Uloga moze biti takmičar/takmicar/admin");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Dodaj korisnika");
        if (!this.tfUsername.getText().equals("") && 
            !this.tfPassword.getText().equals("") && 
            (this.tfRole.getText().equals("takmicar") ||
            this.tfRole.getText().equals("takmičar") ||
            this.tfRole.getText().equals("admin"))) {
                this.pw.println(clientUsername+"-upis:" + tfUsernameA.getText() + ":" + tfPasswordA.getText() + ":" + tfRoleA.getText());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Ukloni korisnika");
        if (!this.tfUsernameA.getText().equals("") && !this.tfPasswordA.getText().equals("") && !this.tfRoleA.getText().equals("")) { 
            this.pw.println(clientUsername + "-brisanje:" + tfUsernameA.getText() + ":" + tfPasswordA.getText() + ":" + tfRoleA.getText());
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void cbSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSetActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na set broj " + cbSet.getSelectedItem().toString());
        this.pw.println(clientUsername + "-" + cbSet.getSelectedItem().toString());
    }//GEN-LAST:event_cbSetActionPerformed

    private void btnNewSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSetActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Nov set pitanja");
        this.pw.println(clientUsername + "-nov set");
    }//GEN-LAST:event_btnNewSetActionPerformed

    private void btnFriendsHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriendsHelpActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Pomoć prijatelja");
        this.btnFriendsHelp.setEnabled(false);
        this.pw.println(this.cbUsers.getSelectedItem().toString() + "-upomoć:" + tfMessage.getText());
    }//GEN-LAST:event_btnFriendsHelpActionPerformed

    private void btnReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Zamena pitanja");
        this.btnReplace.setEnabled(false);
        this.pw.println(clientUsername + "-zamena");
    }//GEN-LAST:event_btnReplaceActionPerformed

    private void btnFiftyFiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiftyFiftyActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Pola-pola");
        this.btnFiftyFifty.setEnabled(false);
        this.pw.println(clientUsername + "-50/50");
    }//GEN-LAST:event_btnFiftyFiftyActionPerformed

    private void btnConfirmRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmRespActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Potvrdi odgovor");
        this.pw.println(clientUsername + "-" + btnGroupResponse.getSelection().getActionCommand());
    }//GEN-LAST:event_btnConfirmRespActionPerformed

    private void btnStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatementActionPerformed
        // TODO add your handling code here:
        System.out.println("Klik na Stanje na tabeli");
        this.pw.println(clientUsername + "-stanje");
    }//GEN-LAST:event_btnStatementActionPerformed

    private void cbUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConfirmResp;
    private javax.swing.JButton btnFiftyFifty;
    private javax.swing.JButton btnFriendsHelp;
    private javax.swing.ButtonGroup btnGroupResponse;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnNewSet;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReplace;
    private javax.swing.JRadioButton btnRespA;
    private javax.swing.JRadioButton btnRespB;
    private javax.swing.JRadioButton btnRespC;
    private javax.swing.JRadioButton btnRespD;
    private javax.swing.JButton btnStatement;
    private javax.swing.JComboBox<String> cbSet;
    private javax.swing.JComboBox<String> cbUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane spQuestions;
    private javax.swing.JTextArea taQuestions;
    private javax.swing.JTextField tfMessage;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPasswordA;
    private javax.swing.JTextField tfRole;
    private javax.swing.JTextField tfRoleA;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfUsernameA;
    // End of variables declaration//GEN-END:variables
}
